name: ✨ Feature Request
description: Suggest an idea or change for Stump
title: '[FEATURE] Give a suitable title'
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: It would be nice if [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I would also be happy with [...]
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Where would this feature be implemented?
      description: Select all that apply. If the documentation on https://www.stumpapp.dev/ will require updating, please tick `Documentation`.
      options:
        - label: Web App
        - label: Mobile App
        - label: Server
        - label: Documentation
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any exta context, screenshots, mockups, etc. about the feature request.
    validations:
      required: false
